name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./1209_app/gradlew
    - name: Build with Gadle check
      run: echo "ls ./1209_app"
    - name: Build with Gradle init
      run: ./1209_app/gradlew init
    - name: Build with Gradle build
      run: ./1209_app/gradlew build
